GreyMatter/play_music.py, README.md, brain.py, main.py
Can you also add import os in the main.py file, as it is being used by sphinx_stt() function?
----
Added ``import os`` to the top of main.py.
* Removed all code and imports not used.
* Put all code into the main() function.
* Added ``r.adjust_for_ambient_noise(source)`` before ``audio = r.listen(source)``. This goes toward replacing passiveListen(). See [Speech Recognition Library Reference](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst) for a descripton of adjust_for_ambient_noise and related options.
This change also seemed to make the dialogue run more smoothly.
* Removed assignments from profile_data to individual variables and replaced the individual variables in the remainder with the equivalent profile_data dictionary element. The reasons …
=> Various Suggestions Pull Request

GreyMatter/SenseCells/tts.py
=> Changed Melissa's voice to female for Linux and Windows platforms.

.travis.yml, README.md, tests/check_profile.py
Added a placeholder test and Travis-CI integration.
=> Add Travis-CI integration

GreyMatter/SenseCells/stt.py, main.py
Fixes https://github.com/Melissa-AI/Melissa-Core/issues/33.
=> Add STT as a separate module

GreyMatter/profile_populator.py
@tanay1337 Fixed the STT error.
=> Fixed UnboundLocalError in profile_populator.py

GreyMatter/SenseCells/stt.py
Provided conversion of profile fields from unicode to ascii to correct PocketSphinx failure error.
Moved decoder set-up before recognition loop to avoid unnecessary reprocessing.
Replaced decoding sequence in recognition loop with code from Jasper to improve recognition quality.
=> Corrected issue PocketSphinx is broken #39

melissa/actions/general_conversations.py
New jokes:
- Why are mountains so funny? Because they are hill areas.
- Have you ever tried to eat a clock? I hear it is very time consuming.
- What happened when the wheel was invented? A revolution.
- What do you call a fake noodle? An impasta!
- Did you hear about that new broom? It is sweeping the nation!
- What is heavy forward but not backward? Ton.
=> Made Melissa funnier by adding new jokes to her repetoire

melissa/actions/general_conversations.py, melissa/actions/horoscope.py, melissa/actions/imgur_handler.py, melissa/actions/ip_address.py, melissa/actions/lighting.py, melissa/actions/notes.py, melissa/actions/play_music.py, melissa/actions/repeat.py, melissa/actions/self_destruct.py, melissa/actions/sleep.py, melissa/actions/system_status.py, melissa/actions/tell_time.py, melissa/actions/twitter_interaction.py, melissa/actions/weather.py, tests/check_profile.py
Added some improvements for #57. Couldn't finish them all because of time, maybe later :)
=> PEP8 improvements

.gitignore, .travis.yml, main.py, melissa/actions/business_news_reader.py, melissa/actions/define_subject.py, melissa/actions/find_iphone.py, melissa/actions/imgur_handler.py, melissa/actions/ip_address.py, melissa/actions/repeat.py, melissa/actions/weather.py, melissa/actions_db.py, melissa/brain.py, melissa/profile.py, melissa/profile_populator.py, melissa/stt.py, melissa/tts.py, melissa/utilities/json_decode.py, setup.cfg, setup/create_lm.py, tests/check_profile.py
@tanay1337 review me please :)
=> chore(flake8-checker): added flake8 checker to TRAVISCI Script

melissa/actions/general_conversations.py
Was not able to squash all commits in last PR and it was also having merge conflicts so created a new PR
=> New chatbot style interaction for general conversation

melissa/actions/tell_time.py
=> Added what_is_date() and what_is_time()

setup.cfg
=> Reformat setup.cfg

requirements.txt
=> Sorts Requirements

melissa/profile_populator.py
This is an implementation of the search described in #106. There is however a problem intrinsic with the package when searching for words with spaces in them, like 'New Delhi', 'New York', etc. It works very well for single worded city names. Test with those. It uses the pywapi api's search city call.
=> add city weather.com search

setup/create_lm.py
This will fix #130, using the code in the issues thread.
=> Fix imports in create_lm.py

requirements-dev.txt
=> Fixes #131

main.py, melissa/profile.py, melissa/profile_loader.py, start.py
Resolves #139 
Both start.py and main.py files do not produce the loading message by calling function load_profile with skip_message as True. The loading message presently displayed is done by the import profile call made by the tts.py module.
=> Duplicacy of Loading message resolved

.travis.yml, README.md, requirements-dev.txt
=> Add coverage

main.py, melissa/actions/imgur_handler.py, melissa/actions_db.py, melissa/profile.py, melissa/utilities/snowboydecoder.py, setup/create_lm.py, setup/travis-build-core.sh, tests/test_actions/test_find_iphone.py, tests/test_profile_loader.py, tests/test_profile_populator.py
=> Fix with codacy

melissa/actions/notification.py, melissa/profile_populator.py, requirements.txt, tests/test_actions/test_notification.py, tests/test_profile_populator.py
I added the file "notification.py" in the actions folder. The file contains a function that can send notifications using pushbullet service. I also updated the "profile_populator.py" file to ask the user for his pushbullet token. According to the user choice, melissa can send information about anything the user request. for example, the user can ask about the weather and after melissa responds the user can ask melissa to send a report of the weather so the user will be able to read it from his/her smartphone.
=> Notification System

start.py
=> fix: usr: catch OSError when using mpg123

requirements-dev.txt, requirements.txt
=> chg: dev: change pywapi pip link

Dockerfile
=> Docker container for Melissa

.gitignore, Aptfile, MANIFEST.in, setup.py
This PR fixes the issue of Template not found which came under the release `0.0.1`
@tanay1337 Please review.
=> Fixes: Template not found

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, Dockerfile
Fixes #187 Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
@tanay1337 Please review, Thanks !!
=> Fixes #187 Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

README.rst
Removal of the badge as that is not a mode of communication that we are using.
Fixes #
-
-
=> Remove chat on Gitter

.github/ISSUE_TEMPLATE.md, README.rst
=> Update Issue Template
